#optional
# version: 'version'
services:
  frontend:
    image: "docker-compose-frontend"
    build: ./frontend
    #birden fazla port yönlendirebilir
    ports:
      - 5173:5173
      - 3000:5173
      - 80:5173
      # 80 verdiğimizde default değer olduğu için port yazmaya gerek kalmaz

   #hata durumunda tekrar başlatır 
    restart: on-failure
    depends_on:
      - backend

  backend:
    image: "docker-compose-backend"
    build: ./backend
    ports:
      - 8000:8000
    
    restart: on-failure
    volumes: #external: internal
      - $PWD/backend/logs:/backend/logs
      - $PWD/backend/upload:/backend/upload
